import {dateKey,tomorrow,clock,minutesOf,progress,overlap,makeDraft,validSlots} from './core.mjs';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),uid=()=>crypto.randomUUID();
const demo=new URLSearchParams(location.search).has('demo'),KEY=demo?'adhd-killer:demo-v3':'adhd-killer:v3';
const empty=()=>({version:3,tasks:[],plans:{},intent:null,sessions:[],running:null,logs:[],corrections:[],templates:{healthy:null,free:null},days:{},reviews:{},draft:null,notes:{}});
let state=empty(),safe=true,allHours=false,editorAction=null,lastHour=new Date().getHours(),shownDay=dateKey(),noticeTimer,recording=null,stream=null,recordPending=false,hold=false,cancelRecording=false,audioURL;
const hm=ms=>new Date(ms).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}),mins=n=>n>=60?`${Math.round(n/6)/10}h`:`${Math.round(n)} 分钟`;
function say(s){$('notice').textContent=s;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('notice').textContent='',6500)}
function save(){if(!safe)return;try{localStorage.setItem(KEY,JSON.stringify(state))}catch{safe=false;say('存储不可用，请导出记录。当前记录保留在页面中。')}}
function migrate(){try{let old=JSON.parse(localStorage.getItem('adhd-killer:v1')||'null');if(!old)return;state.tasks=old.tasks.map(t=>({id:t.id,title:t.text,date:t.day,estimate:0,done:t.done,base:0}));for(let [k,v]of Object.entries(old.goals||{})){let i=k.lastIndexOf(':'),d=k.slice(0,i),h=+k.slice(i+1);let t={id:uid(),title:v,date:d,estimate:60,base:0,done:false};state.tasks.push(t);(state.plans[d]??=[]).push({taskId:t.id,start:h*60,duration:60})}state.sessions=(old.sessions||[]).map(s=>({...s,title:s.purpose,start:s.startedAt,end:s.endedAt}));if(old.active)state.intent={title:old.active.purpose,start:old.active.startedAt,due:old.active.dueAt,returnTitle:'原来的小时目标'};}catch{say('旧版数据未迁移，原始记录仍保留。')}}
const exampleRoutines=(free=false)=>['起床','洗漱','早餐','午餐','晚餐','睡觉'].map((name,i)=>({id:name,name,time:(free?['09:00','09:10','09:30','13:00','19:00','23:50']:['07:30','07:40','08:00','12:30','18:30','23:00'])[i],duration:[0,15,25,40,40,0][i],done:false}));
function seed(){const h=new Date().getHours(),d=dateKey();state.templates.healthy=exampleRoutines();state.templates.free=exampleRoutines(true);state.days[d]={mode:'healthy',routines:exampleRoutines().map((r,i)=>({...r,done:i<3}))};state.tasks=[{id:'demo-1',title:'把作品集的故事讲清楚',date:d,estimate:180,base:120,done:false},{id:'demo-2',title:'读几页，一本喜欢的书',date:d,estimate:30,base:10,done:false},{id:'demo-3',title:'给房间留一点呼吸的空间',date:d,estimate:20,base:20,done:true}];state.plans[d]=[{taskId:'demo-1',start:h*60,duration:60},{taskId:'demo-2',start:Math.min(23,h+1)*60,duration:30}];state.intent={title:'点一份喜欢的晚餐',start:Date.now(),due:Date.now()+5*60000,returnTitle:state.tasks[0].title};}
try{const raw=localStorage.getItem(KEY);if(raw){let x=JSON.parse(raw);if(x.version!==3||!Array.isArray(x.tasks)||!Array.isArray(x.logs))throw Error();state={...empty(),...x}}else{if(demo)seed();else migrate();save()}}catch{safe=false;say('记录无法读取，未覆盖原始数据。请先导出备份。')}
$('demo-banner').hidden=!demo;
function dayData(d=dateKey()){return state.days[d]||{mode:null,routines:[]}}
function task(id){return state.tasks.find(t=>t.id===id)}
function spent(t,at=Date.now()){let n=t.base||0;for(const l of state.logs.filter(l=>l.taskId===t.id))n+=Math.max(0,Math.min(l.end,at)-l.start)/60000;for(const c of state.corrections.filter(c=>c.taskId===t.id&&c.at<=at))n+=c.delta;if(state.running?.taskId===t.id)n+=Math.max(0,at-state.running.start)/60000;return Math.max(0,n)}
function currentTask(){const now=new Date(),m=now.getHours()*60+now.getMinutes();const p=(state.plans[dateKey()]||[]).filter(p=>m>=p.start&&m<p.start+p.duration).at(-1);return task(p?.taskId)}
function pause(at=Date.now()){if(state.running){const boundary=new Date(state.running.start);boundary.setMinutes(60,0,0);state.logs.push({...state.running,end:Math.max(state.running.start,Math.min(at,boundary.getTime())),id:uid()});state.running=null;save()}}
function checkpoint(){const h=new Date().getHours();if(dateKey()!==shownDay||h!==lastHour){if(state.running){let end=new Date();end.setMinutes(0,0,0);pause(end.getTime());say('新的小时到了。原任务计时已停，可选择继续。')}lastHour=h;shownDay=dateKey();render()}}
function openEditor(title,html,action){$('editor-title').textContent=title;$('editor-fields').innerHTML=html;editorAction=action;$('editor').showModal()}
$('editor-close').onclick=$('editor-cancel').onclick=()=>$('editor').close();$('editor-form').onsubmit=e=>{e.preventDefault();try{if(editorAction()!==false){save();$('editor').close();render()}}catch(err){say(err.message)}};
function taskEditor(assign=false){const slot=`${dateKey()}:${new Date().getHours()}`;openEditor(assign?'给这个小时一个方向':'记下一件想做的事',`${assign?`<label>从未完成任务中选择<select id="pick-task"><option value="">或在下面新建</option>${state.tasks.filter(t=>!t.done).map(t=>`<option value="${esc(t.id)}">${esc(t.title)}</option>`).join('')}</select></label>`:''}<label>任务名称<input id="edit-title" maxlength="100" placeholder="例如：完成作品集的项目背景"></label><label>预计总用时（分钟）<input id="edit-estimate" type="number" min="1" max="10080" value="60" required></label>`,()=>{if(assign&&slot!==`${dateKey()}:${new Date().getHours()}`)throw Error('已经跨小时，请关闭后重新选择当前任务');let t=assign?task($('pick-task').value):null;if(!t){let title=$('edit-title').value.trim();if(!title)throw Error('请填写任务名称或选择任务');t={id:uid(),title,date:dateKey(),estimate:+$('edit-estimate').value,base:0,done:false};state.tasks.push(t)}if(assign){pause();const n=new Date(),h=n.getHours(),m=h*60+n.getMinutes(),ps=state.plans[dateKey()]??=[];state.plans[dateKey()]=ps.flatMap(p=>{if(!overlap(m,(h+1)*60,p.start,p.start+p.duration))return [p];const pieces=[];if(p.start<m)pieces.push({...p,duration:m-p.start});if(p.start+p.duration>(h+1)*60)pieces.push({...p,start:(h+1)*60,duration:p.start+p.duration-(h+1)*60});return pieces});state.plans[dateKey()].push({taskId:t.id,start:m,duration:(h+1)*60-m})}say(assign?'这个小时的任务已更新。':'已放进任务书。')})}
function settings(){let mode=dayData().mode||'healthy';openEditor('给生活一个自己的节奏',`<p class="subtle">两套模板都由你决定。未填时间不会自动应用。今天的记录会保留。</p><label>编辑模板<select id="routine-select"><option value="healthy">健康日</option><option value="free">放纵日</option></select></label><div id="routine-fields"></div><label>应用范围<select id="routine-scope"><option value="template">仅保存模板（用于之后的规划）</option><option value="today">模板＋今天的单日设置</option></select></label>`,()=>{const selected=$('routine-select').value;const rs=['起床','洗漱','早餐','午餐','晚餐','睡觉'].map((name,i)=>({id:name,name,time:$('rt-'+i).value,duration:[0,15,25,40,40,0][i],done:false}));if(rs.some(r=>!r.time))throw Error('请填写六项作息时间');state.templates[selected]=rs;if($('routine-scope').value==='today'){const old=dayData();state.days[dateKey()]={...old,mode:selected,routines:rs.map(r=>({...r,done:old.routines.find(x=>x.id===r.id)?.done||false})),previous:old}}say('作息已保存。规划会保护这些时间。')});const populate=()=>{const rs=state.templates[$('routine-select').value]||[];$('routine-fields').innerHTML=['起床','洗漱','早餐','午餐','晚餐','睡觉'].map((name,i)=>`<label class="inline-label">${name}<input id="rt-${i}" type="time" value="${rs.find(r=>r.name===name)?.time||''}" required></label>`).join('')};$('routine-select').value=mode;$('routine-select').onchange=populate;populate()}
$('settings').onclick=$('routine-edit').onclick=settings;$('new-task').onclick=()=>taskEditor();
function renderIntent(){const s=state.intent;$('intent-form').hidden=!!s;$('intent-active').hidden=!s;document.querySelector('.window-frame').classList.toggle('running',!!s);if(s)$('intent-title').textContent=s.title;$('return-goal').textContent=`↳ 做完回到：${s?.returnTitle||currentTask()?.title||'当前小时，再选一件小事。'}`;tick()}
$('intent-form').onsubmit=e=>{e.preventDefault();if(state.intent)return;pause();state.intent={title:$('intent-name').value.trim(),start:Date.now(),due:Date.now()+Number($('intent-minutes').value)*60000,returnTitle:currentTask()?.title||'当前小时'};save();render()};
function finishIntent(done){const s=state.intent;if(!s)return;state.sessions.push({...s,end:Date.now(),completed:done,id:uid()});state.intent=null;save();render();say(done?'这件事做完了。轻轻回到原来的目标。':'记录已留下，不会标为完成。')}
$('intent-finish').onclick=()=>finishIntent(true);$('intent-stop').onclick=()=>finishIntent(false);
function extend(m){if(!state.intent)return;state.intent.due=Math.max(Date.now(),state.intent.due)+m*60000;save();tick()}
$('intent-extend').onclick=()=>extend(5);$('intent-more').onclick=()=>openEditor('再给自己一点时间','<label>延长分钟数<input id="more-min" type="number" min="1" max="240" value="5" required></label>',()=>extend(+$('more-min').value));
function renderRoad(){const now=new Date(),h=now.getHours(),d=dateKey(),ps=state.plans[d]||[],rs=dayData().routines;const start=allHours?0:Math.max(0,h-2),end=allHours?23:Math.min(23,h+2);$('timeline').innerHTML=Array.from({length:end-start+1},(_,i)=>i+start).map(hour=>{const goals=ps.filter(p=>overlap(hour*60,(hour+1)*60,p.start,p.start+p.duration)>0).map(p=>task(p.taskId)?.title).filter(Boolean),rh=rs.filter(r=>Math.floor(minutesOf(r.time)/60)===hour);const label=[...goals,...rh.map(r=>`${r.time} ${r.name}`)].join(' · ')||'留一点空白';if(hour===h){const t=currentTask();return `<div class="road-node now" id="current-door"><time class="road-time">${clock(hour*60)}</time><div class="door"><div class="door-inner"><div class="door-label"><span>YOU ARE HERE · 此刻</span><span>${clock(hour*60)}–${clock((hour+1)*60)}</span></div><h3>${esc(t?.title||rh[0]?.name||'先选一件小事')}</h3><p class="task-detail">${t?`${t.note?esc(t.note)+'<br>':''}已投入 ${mins(spent(t))} / ${t.estimate?`预计 ${mins(t.estimate)}`:'待设置预计用时'}`:'不必安排得很满，从这一小时开始。'}${rh.length?`<br>固定作息：${esc(rh.map(r=>`${r.time} ${r.name}`).join(' · '))}`:''}</p><div class="door-bottom"><div>${t?`<button class="primary" id="task-run">${state.running?.taskId===t.id?'Ⅱ 暂停计时':'开始这一件 →'}</button>`:''}</div><div><button class="quiet" id="change-task">${t?'更换任务':'选择任务'} ↗</button><button class="quiet" id="add-current">＋ 补充</button></div></div></div></div></div>`}const a=new Date(`${d}T${clock(hour*60)}:00`).getTime(),b=a+3600000;const records=state.logs.filter(l=>overlap(a,b,l.start,l.end)>0).map(l=>`${task(l.taskId)?.title||'任务'} · ${mins(overlap(a,b,l.start,l.end)/60000)}`);const intents=state.sessions.filter(s=>overlap(a,b,s.start,s.end)>0).map(s=>`临时：${s.title} · ${mins(overlap(a,b,s.start,s.end)/60000)}`);return `<div class="road-node"><time class="road-time">${clock(hour*60)}</time>${hour<h?`<details class="road-item"><summary>${esc(label)}</summary><p>原计划：${esc(label)}</p><p>实际：${esc([...records,...intents].join('；')||'未记录')}</p></details>`:`<div class="road-item"><span class="readonly">未到 · 只读</span>${esc(label)}</div>`}</div>`}).join('');$('change-task').onclick=()=>taskEditor(true);$('add-current').onclick=()=>{const t=currentTask();if(!t)return taskEditor(true);openEditor('给当前任务补充一句',`<label>下一步 / 说明<input id="task-note" value="${esc(t.note||'')}" maxlength="150"></label>`,()=>{if(currentTask()?.id!==t.id)throw Error('当前任务已变化，请重新打开');t.note=$('task-note').value})};const run=$('task-run');if(run)run.onclick=()=>{const t=currentTask();if(state.intent)return say('先完成或结束临时意图，再开始主任务。');if(state.running)pause();else{if(t.done)return say('这件事已经完成，可以更换任务。');state.running={taskId:t.id,start:Date.now()};save()}render()};}
$('expand-day').onclick=()=>{allHours=!allHours;$('expand-day').textContent=allHours?'收起，回到附近几小时 ↑':'展开完整的 24 小时 ↓';renderRoad()};$('back-now').onclick=()=>$('current-door').scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
function renderBook(){const wasOpen=document.querySelector('.hour-records').open;const ts=state.tasks.filter(t=>t.date===dateKey()||(dayData().taskIds||[]).includes(t.id)||(state.plans[dateKey()]||[]).some(p=>p.taskId===t.id));$('task-pages').innerHTML=ts.length?ts.map(t=>{const n=spent(t),p=progress(n,t.estimate);return `<article class="task-leaf ${t.done?'done':''}"><header><div class="row"><input type="checkbox" aria-label="标记完成 ${esc(t.title)}" data-done="${esc(t.id)}" ${t.done?'checked':''}><h4>${esc(t.title)}</h4></div><span class="percent">${p===null?'—':p+'%'}</span></header><input type="range" data-progress="${esc(t.id)}" aria-label="校正 ${esc(t.title)} 的投入进度" min="0" max="100" step="5" value="${Math.min(100,p||0)}" ${p===null?'disabled':''}><div class="row between"><small>已投入 ${mins(n)} / ${t.estimate?`预计 ${mins(t.estimate)}`:'预计时长未设置'}${t.done?' · 已完成':''}</small><button class="quiet" data-estimate="${esc(t.id)}">校正</button></div>${p>100?'<small>已超出预计用时，任务不会自动标记完成。</small>':''}</article>`}).join(''):'<p class="empty">这一页还空着。<br>记下一件想做的事吧。</p>';
$('task-pages').querySelectorAll('[data-done]').forEach(el=>el.onchange=()=>{const t=task(el.dataset.done);if(state.running?.taskId===t.id)pause();t.done=el.checked;t.completedAt=el.checked?Date.now():null;save();render()});
$('task-pages').querySelectorAll('[data-progress]').forEach(el=>el.onchange=()=>correction(task(el.dataset.progress),Number(el.value)));
$('task-pages').querySelectorAll('[data-estimate]').forEach(el=>el.onclick=()=>{const t=task(el.dataset.estimate);openEditor('校正任务的时间',`<label>预计总用时（分钟）<input id="est" type="number" min="1" max="10080" value="${t.estimate||60}" required></label><label>累计投入（分钟）<input id="used" type="number" min="0" max="100000" value="${Math.round(spent(t))}" required></label><p class="subtle">更新后按新基准重算；差额标为未分配补记，不编造小时记录。</p>`,()=>{pause();state.corrections.push({id:uid(),taskId:t.id,at:Date.now(),delta:+$('used').value-spent(t),oldEstimate:t.estimate});t.estimate=+$('est').value})});
const r=dayData(),done=r.routines.filter(r=>r.done).length;$('routine-mode').textContent=r.mode==='healthy'?'健康日':r.mode==='free'?'放纵日':'待设置';$('routine-percent').textContent=r.routines.length?`${Math.round(done/r.routines.length*100)}%`:'—';$('routine-count').textContent=r.routines.length?`截至目前 · ${done}/${r.routines.length} 项作息`:'先定义你的节奏';$('routines').innerHTML=r.routines.map(x=>`<label class="routine-row"><input type="checkbox" data-routine="${esc(x.id)}" ${x.done?'checked':''}>${esc(x.name)}<time>${esc(x.time)}</time></label>`).join('');$('routines').querySelectorAll('input').forEach(el=>el.onchange=()=>{const r=dayData().routines.find(x=>x.id===el.dataset.routine);r.done=el.checked;r.completedAt=el.checked?Date.now():null;save();renderBook()});renderHour();document.querySelector('.hour-records').open=wasOpen;}
function correction(t,p){const target=t.estimate*p/100;openEditor('确认这次投入校正',`<p>将「${esc(t.title)}」的累计投入校正为 <b>${mins(target)}（${p}%）</b>。</p><p class="subtle">原始计时保留。差额作为未分配补记，不会把任务自动标记完成。</p>`,()=>{if(state.running?.taskId===t.id)pause();const c={id:uid(),taskId:t.id,at:Date.now(),delta:target-spent(t)};state.corrections.push(c);say('已校正，可在小时记录中撤销。')})}
for(let h=0;h<24;h++)$('book-hour').insertAdjacentHTML('beforeend',`<option value="${h}">${clock(h*60)}–${clock((h+1)*60)}</option>`);$('book-hour').value=new Date().getHours();$('book-hour').onchange=renderHour;
function renderHour(){const h=+$('book-hour').value,a=new Date(`${dateKey()}T${clock(h*60)}:00`).getTime(),b=a+3600000;const rows=state.logs.filter(l=>overlap(a,b,l.start,l.end)>0);$('hour-records').innerHTML=rows.map(l=>`<p>${esc(task(l.taskId)?.title)} · 本小时 ${mins(overlap(a,b,l.start,l.end)/60000)}</p>`).join('')||'<p class="subtle">这个小时还没有已结束的计时记录。</p>';const last=state.corrections.at(-1);if(last){$('hour-records').insertAdjacentHTML('beforeend',`<p class="subtle">未分配时段校正：${esc(task(last.taskId)?.title)} ${last.delta>=0?'+':''}${Math.round(last.delta)} 分钟 <button class="quiet" id="undo-correction">撤销最近校正</button></p>`);$('undo-correction').onclick=()=>{const c=state.corrections.pop();if(c.oldEstimate!==undefined)task(c.taskId).estimate=c.oldEstimate;save();renderBook()}}}
function tab(which){$('review-panel').hidden=which!=='review';$('plan-panel').hidden=which!=='plan';$('tab-review').setAttribute('aria-selected',which==='review');$('tab-plan').setAttribute('aria-selected',which==='plan')}$('tab-review').onclick=()=>tab('review');$('tab-plan').onclick=()=>tab('plan');
$('review-date').value=dateKey();$('plan-date').value=tomorrow();$('plan-date').min=tomorrow();
function loadReview(){const d=$('review-date').value;$('review-text').value=state.notes[d]??state.reviews[d]?.text??'';$('review-saved').textContent=state.reviews[d]?'已保存原文，可继续修改后重新确认。':''}
$('review-date').onchange=loadReview;$('review-text').oninput=()=>{state.notes[$('review-date').value]=$('review-text').value;save()};
$('save-review').onclick=()=>{const d=$('review-date').value,s=$('review-text').value.trim();if(!s||!d)return say('请填写复盘日期和内容');if(d>dateKey())return say('复盘日期不能在未来');state.reviews[d]={text:s,confirmedAt:Date.now()};save();loadReview();say('已保存复盘原文。任务用时可在进度书核对、校正。')};
$('plan-text').value=state.planInput||'';$('plan-text').oninput=()=>{state.planInput=$('plan-text').value;save()};
$('make-plan').onclick=()=>{try{const date=$('plan-date').value,mode=$('plan-mode').value;if(date<tomorrow())throw Error('这里仅规划明天及之后的日期');const routines=state.templates[mode];if(!routines)throw Error('先在作息设置中保存所选模式的六项固定时间');const rows=makeDraft($('plan-text').value,routines);if(!rows.length)throw Error('先写下至少一件事');state.draft={id:uid(),date,mode,routines:structuredClone(routines),rows};save();renderDraft()}catch(e){say(e.message)}};
function renderDraft(){const d=state.draft;if(d){$('plan-date').value=d.date;$('plan-mode').value=d.mode}if(!d){$('plan-draft').innerHTML='';return}$('plan-draft').innerHTML=`<p class="eyebrow" style="margin-top:22px">LOCAL DRAFT · 本地规则草稿</p><p class="subtle">${esc(d.date)} · ${d.mode==='healthy'?'健康日':'放纵日'} · 保留 20% 可用时间为缓冲</p>${d.rows.map((r,i)=>`<div class="draft-row ${r.start===null?'unplaced':''}"><input type="time" aria-label="${esc(r.title)} 开始时间" data-draft-time="${i}" value="${r.start===null?'':clock(r.start)}"><span>${esc(r.title)} <small>${r.duration} 分钟${r.suggested?' · 建议时长':''}${r.start===null?' · 待安排':''}</small></span><button class="quiet" data-remove-slot="${i}" aria-label="将 ${esc(r.title)} 留待安排">×</button></div>`).join('')}<details class="subtle"><summary>查看受保护的固定作息</summary>${d.routines.map(r=>`<p>${esc(r.time)} ${esc(r.name)}</p>`).join('')}</details><p class="subtle">清空时间可留待安排。确认前不会改动正式时间线。</p><button id="confirm-plan" class="primary">确认 ${esc(d.date)} 的规划</button>`;$('plan-draft').querySelectorAll('[data-draft-time]').forEach(el=>el.onchange=()=>{d.rows[+el.dataset.draftTime].start=el.value?minutesOf(el.value):null;save()});$('plan-draft').querySelectorAll('[data-remove-slot]').forEach(el=>el.onclick=()=>{d.rows[+el.dataset.removeSlot].start=null;save();renderDraft()});$('confirm-plan').onclick=()=>{if(d.date<tomorrow())return say('草稿日期已过期，请重新生成');const error=validSlots(d.rows,d.routines);if(error)return say(error);const apply=()=>{state.days[d.date]={mode:d.mode,routines:d.routines.map(r=>({...r,done:false}))};const plan=[],taskIds=[];for(const row of d.rows){let t=state.tasks.find(t=>t.title===row.title&&!t.done);if(!t){t={id:uid(),title:row.title,date:d.date,estimate:row.duration,base:0,done:false};state.tasks.push(t)}taskIds.push(t.id);if(row.start!==null)plan.push({taskId:t.id,start:row.start,duration:row.duration})}state.days[d.date].taskIds=taskIds;state.plans[d.date]=plan;state.draft=null;save();renderDraft();say('明日规划已确认，到对应日期会显示在时间之路。')};if(state.plans[d.date]?.length)openEditor('更新已确认的明日规划',`<p>将替换 ${esc(d.date)} 的时间安排，任务及已有投入不会删除。</p>`,apply);else apply()};}
async function startRecord(){if(recording||recordPending)return;recordPending=true;cancelRecording=false;$('record-status').textContent='正在请求麦克风…';try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw Error('此浏览器暂不支持录音，请使用文字输入');stream=await navigator.mediaDevices.getUserMedia({audio:true});if(!hold){stream.getTracks().forEach(t=>t.stop());$('record-status').textContent='已松开，请再次按住话筒录音';return}let chunks=[];recording=new MediaRecorder(stream);recording.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recording.onstop=()=>{stream.getTracks().forEach(t=>t.stop());if(!cancelRecording&&chunks.length){if(audioURL)URL.revokeObjectURL(audioURL);audioURL=URL.createObjectURL(new Blob(chunks,{type:recording?.mimeType||chunks[0].type}));$('record-audio').src=audioURL;$('record-audio').hidden=false;$('record-status').textContent='录音已保留，可回听；转写模型尚未连接。'}else $('record-status').textContent='已取消，声音未保存';recording=null;$('record-toggle').textContent='点击录音';$('record-cancel').hidden=true;document.querySelector('.stage-art').classList.remove('recording')};recording.start();$('record-status').textContent='正在录音 · 松开结束';$('record-toggle').textContent='停止录音';$('record-cancel').hidden=false;document.querySelector('.stage-art').classList.add('recording')}catch(e){say(e.name==='NotAllowedError'?'未获得麦克风权限，可以直接输入文字。':e.message);$('record-status').textContent='可以先用文字，把今天留下来';hold=false}finally{recordPending=false}}
function stopRecord(){hold=false;if(recording?.state==='recording')recording.stop()}
$('mic').onpointerdown=e=>{e.preventDefault();hold=true;$('mic').setPointerCapture(e.pointerId);startRecord()};$('mic').onpointerup=stopRecord;$('mic').onpointercancel=()=>{cancelRecording=true;stopRecord()};$('mic').onkeydown=e=>{if((e.key===' '||e.key==='Enter')&&!e.repeat){e.preventDefault();hold=true;startRecord()}};$('mic').onkeyup=e=>{if(e.key===' '||e.key==='Enter')stopRecord()};$('record-toggle').onclick=()=>{if(recording||recordPending)stopRecord();else{hold=true;startRecord()}};$('record-cancel').onclick=()=>{cancelRecording=true;stopRecord()};document.addEventListener('visibilitychange',()=>{if(document.hidden)stopRecord();else{checkpoint();render()}});
function tick(){const now=Date.now();$('live-clock').textContent=new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});if(state.intent){const s=state.intent,n=Math.max(0,Math.ceil((s.due-now)/1000));$('countdown').textContent=`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;$('intent-time').textContent=`${hm(s.start)} 开始 · ${hm(s.due)} 预计结束${n===0?' · 时间到了，回到目标吗？':''}`}}
function render(){$('date-label').textContent=new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'short'});$('mode-stamp').innerHTML=dayData().mode?`${dayData().mode==='healthy'?'健康日':'放纵日'}<br>自己的节奏`:'我的一天<br>慢慢来也可以';renderIntent();renderRoad();renderBook()}
$('export').onclick=()=>{let a=document.createElement('a'),u=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.href=u;a.download=`回到此刻-${dateKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
// Local previews bypass old caches; deployed PWA keeps offline support with versioned assets.
if('serviceWorker'in navigator){if(['localhost','127.0.0.1'].includes(location.hostname)){navigator.serviceWorker.getRegistrations().then(rs=>rs.filter(r=>r.scope===new URL('./',location.href).href).forEach(r=>r.unregister()))}else navigator.serviceWorker.register('./sw.js').then(()=>$('offline-status').textContent='离线支持已注册').catch(()=>$('offline-status').textContent='离线缓存暂不可用')}
if(state.running){state.pendingTimer=state.running;state.running=null;save()}
loadReview();renderDraft();render();if(state.pendingTimer){const pending=state.pendingTimer;openEditor('核对上一次的计时',`<p>「${esc(task(pending.taskId)?.title)}」上次未结束。请确认实际投入，未确认前不计入任务。</p><label>实际投入（分钟）<input id="recovered-min" type="number" min="0" max="1440" value="0" required></label><p class="subtle">差额记为未分配补记，不猜测后台是否一直在工作。</p>`,()=>{state.corrections.push({id:uid(),taskId:pending.taskId,at:Date.now(),delta:+$('recovered-min').value});state.pendingTimer=null;say('已核对上次投入。')})}setInterval(()=>{checkpoint();tick()},1000);setInterval(()=>{if(state.running&&!$('editor').open&&document.activeElement?.type!=='range')renderBook()},10000);
